### PR TITLE
docs: Adding doesn't have an ego

### PR DESCRIPTION
**Pull request by th3morg**
Thought this would be a good one to add... but I'm a 1x engineer, so it won't hurt my feelings if it isn't accepted ;)

### CODE REVIEW

**Comment by simskij** [comment]
Totally agree. This is nitpicking, so feel free to just ignore it:

Would it make sense to phrase it "Does not let their ego do the talking" to pinpoint that a 1x engineer likely still has an ego, but won't let it control how they act?

**Comment by th3morg** [comment]
Sure, I like that :)

**Comment by simskij** [comment]
Hey @bnb and @maddhruv - is this project dead? 😸

**Comment by bnb** [comment]
I get the intent here but I can see this being weaponized against marginalized folks who are doing the same kinds of things as the most privileged engineers. Perhaps refining this idea into something that does not include "ego" would be passable.

**Comment by th3morg** [comment]
Okay. Feel free to decline this PR. Thanks for having a look.

**Pull request closed without merging**
