### PR TITLE
Added Productive Discussions Trait

### PR DESCRIPTION
**Pull request by Andrei15193**
Discussions are at the foundation of any team, a 1x engineer will always want to have productive discussions with the team before making a decision that affects the overall process, code base or anything related to what the team is doing.

E.g.: More OOP or more FP? How are we addressing versioning? How are we integrating with what other teams are doing? How are we discussing with other teams, if at all? Do we really need to use library/framework X just because it is new or suits our immediate needs? Why aren't we closing most stories by the end of the spring? Why are we rushing them at the end of the spring? Is Scrum really the best pick for what we're doing, what are the alternatives? How are we deploying our application and how do we communicate this to our users?

### CODE REVIEW

**Comment by bnb** [comment]
I really like how you framed this as "Discussions" in the PR comment. Since debates can be seen as adversarial, would you be willing to reframe "debate" to "discussions" in the code as well?

**Comment by Andrei15193** [comment]
I do like _discussions_ more than _debates_. As you said, the latter has some connotation to what would rather be counterproductive.

**Comment by bnb** [comment]
I'm iffy on the final sentence, but if others feel the same way they can open a PR against it. Merging 👍

**Comment by Andrei15193** [comment]
Sounds good to me :)

**Pull request merged**
