### PR TITLE
New trait

### PR DESCRIPTION
**Pull request by michaeltintiuc**
Added new trait `Uses available tools to find the author of the bug`

### CODE REVIEW

**Comment by bnb** [comment]
There's a few things that don't necessarily align with the intent of the project here:

- Not everyone is able to use git for their work.
- Assumes that 1x engineers are male-identifying.

If you'd like to try to refine the underlying concept you're trying to convey with the message, feel free to update the PR 👍

**Comment by michaeltintiuc** [comment]
Thanks for your kind reply @bnb, rephrased it.

**Comment by bnb** [comment]
I suppose my follow up question:

Uses the tools for what purpose? What is the outcome they're looking for?

**Comment by michaeltintiuc** [comment]
The idea was lost somewhere in political correctness.

**Pull request closed without merging**
