### PR TITLE
feat: improvement to add logos

### PR DESCRIPTION
**Pull request by KathyReid**
Hi there, 

I've done some possible logo designs that might be good on t-shirts :-) 

Comments and feedback warmly welcomed. 

Best, Kathy

### CODE REVIEW

**Comment by KathyReid** [comment]
I'm finding the Semantic Pull Request pretty frustrating - I don't know what it's checking for - I thought the PR title was reasonably clear 😞

**Comment by KathyReid** [comment]
Partial fix for #78

**Comment by bnb** [comment]
Fixed the semantic pull request check 👍

Will think on the logos. I do enjoy just being able to include a font via CSS and have the correct branding for the ease of implementation.

**Comment by KathyReid** [comment]
Thanks :-) 
And no worries, being able just to use text makes things a lot easier. 
Best, Kathy

**Comment by KathyReid** [comment]
I'm cleaning up my outstanding PRs and Issues, closing this :-)

**Pull request closed without merging**
